### ISSUE TITLE
Prevent code from linting

### ISSUE THREAD

**Issue by nodaguti** [nodaguti/textlint-rule-spellchecker#2]
As described in textlint/textlint/issues/166, the current implementation fails to avoid linting code blocks.

**Comment by nodaguti** [comment]
5887ca53e01e59305e5fcb7d8cb341f751e5f3e5
18e0ad5c30718d6320103ed71d8392adc2a31bfe

**Comment by azu** [comment]
I'v created a example for handling Paragraph https://github.com/azu/textlint-rule-en-max-word-count 
And add document to texlint https://github.com/textlint/textlint/blob/master/docs/rule-advanced.md

It is much appreciated if It might help you :)

**Comment by nodaguti** [comment]
Excellent, thank you!
Creating a rule against `Syntax.Paragraph` requires lots of things to consider...
