### ISSUE TITLE
Allow passing ignored words/patterns

### ISSUE THREAD

**Issue by jrencz** [nodaguti/textlint-rule-spellchecker#46]
I'm considering using this rule as a complementary to [`eslint-plugin-spellcheck`](https://www.npmjs.com/package/eslint-plugin-spellcheck) and I wonder if it's possible to define skipped words exception list.

Use case: The project may have its own set of words that have domain-related meaning and I don't want them to be considered errors although they don't fit the general dictionary.

How about introducing configuration similar to what ESLint plugin has: skipWords and skipIfMatch (names may off course be different)

What I'd like to achieve is to make it possible to maintain one and only one set of words that are excluded.

**Comment by nodaguti** [comment]
Thank you for your feedback.

I was initially thinking that it would be better to delegate the 'skipWords' functionality to the spellchecker side as I've mentioned in the "Notes" section of ReadME, i.e., asking users to register their own list to a spellchecker's ignorance list, but I'm now convinced that there is some use cases where you want to share your configuration.

I'm going to start working on this shortly. Thank you again.

**Comment by nodaguti** [comment]
@jrencz 
I'm really sorry for being inactive for quite a long time.

If you are still around and interested in using this rule, I'd be glad to announce that I've released v2.2.0 which has [skip words, regular expressions and TxtAST node types features](https://github.com/textlint-rule/textlint-rule-spellchecker#ignoring-words).

Thanks again for your suggestions and hope you will be happy with this release!
